
INSERT [dbo].[EstudioComplementario] ([Id], [Nombre], [Descripcion], [Costo], [TiempoEspera]) VALUES (1, N'Análisis de sangre completo (hemograma)', NULL, CAST(100.00 AS Decimal(18, 2)), NULL)
INSERT [dbo].[EstudioComplementario] ([Id], [Nombre], [Descripcion], [Costo], [TiempoEspera]) VALUES (2, N'Prueba de glucosa en sangre', NULL, CAST(10.00 AS Decimal(18, 2)), NULL)
INSERT [dbo].[EstudioComplementario] ([Id], [Nombre], [Descripcion], [Costo], [TiempoEspera]) VALUES (3, N'Prueba de colesterol', NULL, CAST(20.00 AS Decimal(18, 2)), NULL)
INSERT [dbo].[EstudioComplementario] ([Id], [Nombre], [Descripcion], [Costo], [TiempoEspera]) VALUES (4, N'Radiografía (una zona)', NULL, CAST(100.00 AS Decimal(18, 2)), NULL)
INSERT [dbo].[EstudioComplementario] ([Id], [Nombre], [Descripcion], [Costo], [TiempoEspera]) VALUES (5, N'Ultrasonido', NULL, CAST(150.00 AS Decimal(18, 2)), NULL)
INSERT [dbo].[EstudioComplementario] ([Id], [Nombre], [Descripcion], [Costo], [TiempoEspera]) VALUES (6, N'Resonancia magnética (MRI)', NULL, CAST(400.00 AS Decimal(18, 2)), NULL)
INSERT [dbo].[EstudioComplementario] ([Id], [Nombre], [Descripcion], [Costo], [TiempoEspera]) VALUES (7, N'Tomografía computarizada (CT)', NULL, CAST(500.00 AS Decimal(18, 2)), NULL)
INSERT [dbo].[EstudioComplementario] ([Id], [Nombre], [Descripcion], [Costo], [TiempoEspera]) VALUES (8, N'Electrocardiograma (ECG o EKG)', NULL, CAST(50.00 AS Decimal(18, 2)), NULL)
INSERT [dbo].[EstudioComplementario] ([Id], [Nombre], [Descripcion], [Costo], [TiempoEspera]) VALUES (9, N'Prueba de función pulmonar (espirometría)', NULL, CAST(40.00 AS Decimal(18, 2)), NULL)
INSERT [dbo].[EstudioComplementario] ([Id], [Nombre], [Descripcion], [Costo], [TiempoEspera]) VALUES (10, N'Prueba de densidad ósea (DEXA scan)', NULL, CAST(150.00 AS Decimal(18, 2)), NULL)
INSERT [dbo].[EstudioComplementario] ([Id], [Nombre], [Descripcion], [Costo], [TiempoEspera]) VALUES (11, N'Mamografía', NULL, CAST(100.00 AS Decimal(18, 2)), NULL)
INSERT [dbo].[EstudioComplementario] ([Id], [Nombre], [Descripcion], [Costo], [TiempoEspera]) VALUES (12, N'Colonoscopia', NULL, CAST(1000.00 AS Decimal(18, 2)), NULL)
INSERT [dbo].[EstudioComplementario] ([Id], [Nombre], [Descripcion], [Costo], [TiempoEspera]) VALUES (13, N'Prueba de esfuerzo cardíaco', NULL, CAST(200.00 AS Decimal(18, 2)), NULL)
INSERT [dbo].[EstudioComplementario] ([Id], [Nombre], [Descripcion], [Costo], [TiempoEspera]) VALUES (14, N'Endoscopia', NULL, CAST(1000.00 AS Decimal(18, 2)), NULL)
INSERT [dbo].[EstudioComplementario] ([Id], [Nombre], [Descripcion], [Costo], [TiempoEspera]) VALUES (15, N'Biopsia', NULL, CAST(1000.00 AS Decimal(18, 2)), NULL)
