
INSERT INTO Servicio ( Nombre, Acronimo, Descripcion) VALUES
('Oncología', 'ONC', 'Servicio de oncología'),
('Neurología', 'NEU', 'Servicio de neurología'),
('Pediatría', 'PED', 'Servicio de pediatría'),
('Dermatología', 'DER', 'Servicio de dermatología'),
('Neumología', 'NE', 'Servicio de neumología'),
( 'Endocrinología', 'EN', 'Servicio de endocrinología'),
( 'Nefrología', 'NEF', 'Servicio de nefrología'),
( 'Geriatría', 'GE', 'Servicio de geriatría'),
( 'Cirugía General', 'CG', 'Servicio de cirugía general'),
( 'Anestesiología', 'AN', 'Servicio de anestesiología'),
( 'Rehabilitación', 'RE', 'Servicio de rehabilitación'),
( 'Psiquiatría', 'PS', 'Servicio de psiquiatría'),
( 'Radiología', 'RA', 'Servicio de radiología'),
( 'Medicina de Urgencias', 'MU', 'Servicio de medicina de urgencias'),
( 'Otorrinolaringología', 'ORL', 'Servicio de otorrinolaringología'),
( 'Inmunología', 'IN', 'Servicio de inmunología'),
( 'Gastroenterología', 'GA', 'Servicio de gastroenterología'),
( 'Terapia Física', 'TF', 'Servicio de terapia física'),
( 'Infectología', 'IF', 'Servicio de infectología'),
( 'Medicina Familiar', 'MF', 'Servicio de medicina familiar'),
( 'Toxicología', 'TO', 'Servicio de toxicología'),
( 'Cirugía Plástica', 'CP', 'Servicio de cirugía plástica'),
( 'Medicina del Deporte', 'MD', 'Servicio de medicina del deporte'),
( 'Urgencias Pediátricas', 'UP', 'Servicio de urgencias pediátricas'),
( 'Neurocirugía', 'NC', 'Servicio de neurocirugía'),
( 'Patología', 'PA', 'Servicio de patología'),
( 'Genética Médica', 'GM', 'Servicio de genética médica'),
( 'Cuidados Paliativos', 'CP', 'Servicio de cuidados paliativos'),
( 'Salud Mental', 'SM', 'Servicio de salud mental');
